[loggers]
keys=root,backup

[handlers]
keys=logconsole,logfile_scanner,logfile_backup

[formatters]
keys=logfileformatter

[logger_root]
level=DEBUG
handlers=logconsole,logfile_scanner

[logger_backup]
level=INFO
handlers=logconsole,logfile_backup
qualname=backup
propagate=0

[formatter_logfileformatter]
format=[%(asctime)s] %(name)s: [%(levelname)s] --- %(message)s

[handler_logconsole]
class=StreamHandler
formatter=logfileformatter

[handler_logfile_scanner]
class=handlers.RotatingFileHandler
level=NOTSET
args=('logs/scanner.log','a', 10*1024*1024, 5)
formatter=logfileformatter

[handler_logfile_backup]
class=handlers.RotatingFileHandler
level=NOTSET
args=('logs/backup.log','a', 5*1024*1024, 3)
formatter=logfileformatter