import sqlite3
from datetime import datetime
import xml.etree.ElementTree as ET
from dataclasses import dataclass


@dataclass
class Host:
    ip_address: str
    mac_address: str
    vendor: str
    last_seen: datetime

    def to_sqlite_row(self):
        """Converts the dataclass to a tuple for DB insertion."""
        return (
            self.ip_address,
            self.mac_address,
            self.vendor,
            self.last_seen.isoformat(),
        )


def get_xml_hosts(xml_file):
    """Parses xml generated by nmap"""
    tree = ET.parse(xml_file)
    root = tree.getroot()
    nmap_start = root.attrib.get("startstr")
    nmap_start = datetime.strptime(nmap_start, "%a %b %d %H:%M:%S %Y")
    hosts = []
    for host in root.findall("host"):
        ip = mac = vendor = None
        for addr in host.findall("address"):
            if addr.attrib["addrtype"] == "ipv4":
                ip = addr.attrib["addr"]
            elif addr.attrib["addrtype"] == "mac":
                mac = addr.attrib["addr"]
                vendor = addr.attrib.get("vendor")
        host = Host(ip, mac, vendor, nmap_start)
        hosts.append(host)
    return hosts


def update_database(xml_file, db_file):
    hosts = get_xml_hosts(xml_file)
    host_data = [host.to_sqlite_row() for host in hosts]
    conn = sqlite3.connect(db_file)
    cursor = conn.cursor()
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS hosts (
            ip TEXT PRIMARY KEY,
            mac TEXT,
            vendor TEXT,
            last_seen TEXT
        )
    """
    )
    cursor.executemany(
        """
        INSERT OR REPLACE INTO hosts (ip, mac, vendor, last_seen)
        VALUES (?, ?, ?, ?)
    """,
        host_data,
    )
    conn.commit()
    conn.close()
